line-length = 88
target-version = "py311"

[lint]
select = ["E", "F", "W", "I"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"


